import puppeteer from "puppeteer";
import Handlebars from "handlebars";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const s3 = new S3Client({
  region: process.env.DO_SPACES_REGION || "us-east-1",
  endpoint: process.env.DO_SPACES_ENDPOINT,
  credentials: {
    accessKeyId: process.env.DO_SPACES_KEY || "",
    secretAccessKey: process.env.DO_SPACES_SECRET || "",
  },
});

const BUCKET = process.env.DO_SPACES_BUCKET || "edumatch-uploads";

export type QuotePdfData = {
  quoteId: string;
  studentName: string;
  tutorName: string;
  subject: string;
  gradeLevel: string;
  hourlyRate: number;
  estimatedHours: number;
  totalAmount: number;
  currency: string;
  notes?: string;
  availabilitySlots: Array<{ day: string; time: string }>;
  createdAt: string;
  expiresAt: string;
};

const quoteTemplate = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Quote #{{quoteId}}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #333; }
    .header { text-align: center; margin-bottom: 40px; }
    .header h1 { color: #059669; margin: 0; }
    .header p { color: #666; margin: 8px 0 0; }
    .section { margin: 30px 0; }
    .section h2 { color: #374151; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
    .row { display: flex; justify-content: space-between; margin: 12px 0; }
    .label { color: #6b7280; }
    .value { font-weight: 600; }
    .total { background: #ecfdf5; padding: 20px; border-radius: 8px; margin-top: 30px; }
    .total .row { font-size: 18px; }
    .slots { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }
    .slot { background: #f3f4f6; padding: 8px 12px; border-radius: 4px; font-size: 14px; }
    .footer { margin-top: 60px; text-align: center; color: #9ca3af; font-size: 12px; }
    .expires { background: #fef3c7; padding: 12px; border-radius: 6px; text-align: center; margin: 20px 0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>EduMatch Quote</h1>
    <p>Quote #{{quoteId}}</p>
  </div>

  <div class="section">
    <h2>Student Information</h2>
    <div class="row">
      <span class="label">Name:</span>
      <span class="value">{{studentName}}</span>
    </div>
  </div>

  <div class="section">
    <h2>Tutor Information</h2>
    <div class="row">
      <span class="label">Name:</span>
      <span class="value">{{tutorName}}</span>
    </div>
  </div>

  <div class="section">
    <h2>Session Details</h2>
    <div class="row">
      <span class="label">Subject:</span>
      <span class="value">{{subject}}</span>
    </div>
    <div class="row">
      <span class="label">Grade Level:</span>
      <span class="value">{{gradeLevel}}</span>
    </div>
    <div class="row">
      <span class="label">Hourly Rate:</span>
      <span class="value">{{currency}} {{hourlyRate}}</span>
    </div>
    <div class="row">
      <span class="label">Estimated Hours:</span>
      <span class="value">{{estimatedHours}} hours</span>
    </div>
  </div>

  <div class="section">
    <h2>Availability</h2>
    <div class="slots">
      {{#each availabilitySlots}}
        <div class="slot">{{day}} at {{time}}</div>
      {{/each}}
    </div>
  </div>

  {{#if notes}}
  <div class="section">
    <h2>Notes</h2>
    <p>{{notes}}</p>
  </div>
  {{/if}}

  <div class="total">
    <div class="row">
      <span class="label">Total Amount:</span>
      <span class="value">{{currency}} {{totalAmount}}</span>
    </div>
  </div>

  <div class="expires">
    <strong>Quote expires:</strong> {{expiresAt}}
  </div>

  <div class="footer">
    <p>Generated by EduMatch on {{createdAt}}</p>
    <p>Accept this quote at https://edumatch.asafarim.com/student</p>
  </div>
</body>
</html>
`;

const template = Handlebars.compile(quoteTemplate);

export async function generateQuotePdf(data: QuotePdfData): Promise<{ url: string; key: string }> {
  // Launch browser
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  // Generate HTML
  const html = template(data);

  // Render PDF
  await page.setContent(html, { waitUntil: "networkidle0" });
  const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });
  await browser.close();

  // Upload to DO Spaces
  const key = `quotes/${data.quoteId}-${Date.now()}.pdf`;
  const command = new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    Body: pdfBuffer,
    ContentType: "application/pdf",
  });

  await s3.send(command);

  // Generate signed URL (7 days)
  const signedUrl = await getSignedUrl(
    s3,
    new PutObjectCommand({ Bucket: BUCKET, Key: key }),
    { expiresIn: 7 * 24 * 60 * 60 }
  );

  return { url: signedUrl.replace("?", ".pdf?").replace("x-amz-meta-sdk-checksum", "response-content-disposition=attachment"), key };
}
