/**
 * Terms of Service for Vionto
 */

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)] px-5 py-12">
      <div className="mx-auto max-w-3xl">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
        <p className="text-sm text-[var(--color-text-muted)] mb-8">Last updated: May 8, 2026</p>

        <div className="prose prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Vionto ("the Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p>
              Vionto is an AI-powered service that transforms your photos into narrated video stories. 
              Features include script generation, text-to-speech narration, video rendering, and export to various formats.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Account Responsibilities</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Ensuring the information you provide is accurate and complete</li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Subscription Plans and Billing</h2>
            <p>
              Vionto offers free and paid subscription plans. Paid plans are billed monthly or annually as selected. 
              You agree to pay all fees incurred under your plan. We reserve the right to modify pricing at any time with 30 days notice.
            </p>
            <p className="mt-2">
              <strong>Quotas:</strong> Each plan has limits on images, storage, TTS seconds, render minutes, and exports. 
              Overage charges apply when limits are exceeded.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Content and Usage</h2>
            <p>You retain ownership of content you upload to Vionto. By using the Service, you grant us a license to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Process your images to generate videos using AI models</li>
              <li>Store your content in our secure cloud infrastructure</li>
              <li>Deliver generated videos to you for download</li>
            </ul>
            <p className="mt-2">
              <strong>You represent and warrant that:</strong> you own or have the right to upload all content,
              and your content does not violate any law or third-party rights.
            </p>
            <p className="mt-2">
              <strong>Imported photos:</strong> When you import photos from Google Photos or a shared
              album link, you confirm you have the right to use those photos, and you authorize Vionto
              to fetch the photos you select to create your videos. Vionto&rsquo;s use of Google user
              data complies with the{" "}
              <a
                href="https://developers.google.com/terms/api-services-user-data-policy"
                className="underline"
                target="_blank"
                rel="noreferrer"
              >
                Google API Services User Data Policy
              </a>{" "}
              (Limited Use). See our Privacy Policy for details.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. AI Content and Provenance</h2>
            <p>
              Videos generated by Vionto contain AI-generated narration and audio. We maintain provenance logs 
              recording the AI provider, model, prompt version, and render manifest for each export.
            </p>
            <p className="mt-2">
              You are responsible for ensuring that AI-generated content complies with applicable laws, including disclosure requirements for synthetic media.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Prohibited Uses</h2>
            <p>You may not use Vionto to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Create deepfakes, non-consensual intimate imagery, or deceptive content</li>
              <li>Generate content that promotes violence, hate speech, or illegal activities</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Harass, abuse, or threaten others</li>
              <li>Attempt to reverse-engineer or circumvent our security measures</li>
              <li>Use the Service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Content Moderation</h2>
            <p>
              We use automated content moderation tools to screen generated content. Content flagged as unsafe may be blocked, 
              flagged for review, or removed. We reserve the right to suspend or terminate accounts that repeatedly violate our content policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Service Availability</h2>
            <p>
              We strive for 99.5% uptime but do not guarantee uninterrupted service. We may suspend service for maintenance, 
              updates, or emergencies. We are not liable for any loss or damage from service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Termination</h2>
            <p>
              We may suspend or terminate your account at any time for violation of these terms or abuse of the Service. 
              Upon termination, your right to use the Service ceases immediately. You may delete your account at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" without warranties of any kind, express or implied. We do not warrant that 
              the Service will be error-free, secure, or uninterrupted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, our liability is limited to the amount you paid for the Service in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Governing Law</h2>
            <p>
              These terms are governed by the laws of the Netherlands. Any disputes will be resolved in the courts of Amsterdam.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">14. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. Material changes will be notified by email or posted on our Service. 
              Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">15. Contact Us</h2>
            <p>
              For questions about these terms, contact us at:
            </p>
            <p className="mt-2">
              <strong>Email:</strong> legal@asafarim.com<br />
              <strong>Address:</strong> ASafariM Digital, Amsterdam, Netherlands
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
