import type { RoadmapItem } from "@asafarim/ui";

const PR = (n: number) => ({
  label: `PR #${n}`,
  href: `https://github.com/AliSafari-IT/asafarim-platform/pull/${n}`,
});

const ISSUE = (n: number) => ({
  label: `#${n}`,
  href: `https://github.com/AliSafari-IT/asafarim-platform/issues/${n}`,
});

/**
 * Testora's direction. The left column is what already runs in the app,
 * including the now-closed "autonomous quality loop" epic (#269) — Testora's
 * bidirectional TasksAI integration. The right column is the next epic:
 * an AI-native quality assistant (#629) that helps find and explain
 * failures, not just write them up after the fact.
 */
export const roadmapItems: RoadmapItem[] = [
  {
    id: "Authoring",
    title: "Requirements → suites → fixtures → cases",
    status: "shipped",
    summary:
      "The full authoring model — functional requirements, test suites, fixtures, and cases (single, multi, or raw scripted) — persisted in Testora's own PostgreSQL, kept separate from the shared platform schema.",
    tags: ["core"],
  },
  {
    id: "Execution",
    title: "Live TestCafe execution with streamed progress",
    status: "shipped",
    summary:
      "Testers drive a real headless browser against local or remote targets and watch run progress stream in over SSE. Repeat runs per case, and a per-fixture flaky flag that adds retries.",
  },
  {
    id: "Targets",
    title: "Per-app target environments",
    status: "shipped",
    summary:
      "Each app under test carries its own Local / Remote (and user-added) environments; switching apps offers that app's own targets. Seeded entries are reconciled from code, custom ones are preserved.",
  },
  {
    id: "Results",
    title: "Results, failure screenshots & AI issue drafting",
    status: "shipped",
    summary:
      "Every run stored with pass/fail status, duration, and a failure screenshot captured automatically. A failing result becomes a ready-to-file GitHub issue — drafted by AI when a key is set, from a deterministic template otherwise — and published to GitHub with two-way open/closed state.",
    tags: ["triage"],
  },
  {
    id: "Access",
    title: "Public landing, private apps-under-test",
    status: "shipped",
    summary:
      "A public catalog and marketing surface; individual apps under test can be locked behind a key, with their catalog and results withheld server-side until unlocked.",
  },
  {
    id: "Benchmark",
    title: "Committed benchmark evidence",
    status: "in-progress",
    summary:
      "The benchmark results published on Showcase are committed snapshots from a seeded sample app. Broadening coverage and keeping the snapshots current is ongoing.",
    tags: ["showcase"],
  },

  // ── Autonomous quality loop — epic #269 (closed 12 Aug 2026) ──────
  {
    id: "#258",
    title: "Run-artifact bundle API",
    status: "shipped",
    timeframe: "Loop · foundation",
    summary:
      "Exports one result as a versioned JSON bundle — error, step/assertion timeline, screenshot, and a reference to the previous passing run — so another system can consume a failure cleanly, gated by the same visibility check the results page uses.",
    tags: ["epic #269"],
    links: [ISSUE(258)],
  },
  {
    id: "#259",
    title: "Richer failure artifacts",
    status: "shipped",
    timeframe: "Loop · foundation",
    summary:
      "A DOM snapshot and a structured step timeline are captured at the point of failure, stored in object storage with a retention window instead of multi-MB data URLs on the result row.",
    tags: ["epic #269"],
    links: [ISSUE(259)],
  },
  {
    id: "#260",
    title: "Automatic flake detection + quarantine",
    status: "shipped",
    timeframe: "Loop",
    summary:
      "Flakiness is derived from fail-then-pass across repeat runs, and a quarantine state keeps a flaky test out of the blocking set while it's still being investigated.",
    tags: ["epic #269"],
    links: [ISSUE(260)],
  },
  {
    id: "#261",
    title: "Outbound signed webhooks",
    status: "shipped",
    timeframe: "Loop",
    summary:
      "An HMAC-signed dispatcher for run.completed / regression.detected / flake.detected / check.satisfied, with a delivery log and retries — the channel that tells TasksAI something happened.",
    tags: ["epic #269"],
    links: [ISSUE(261)],
  },
  {
    id: "#262",
    title: "Inbound provisioning + pending scenarios",
    status: "shipped",
    timeframe: "Loop · TDD gate",
    summary:
      "Accepts a request from TasksAI to register pending test scenarios for a feature's acceptance criteria — scaffolds generated by the existing generators, marked pending until real assertions land.",
    tags: ["epic #269"],
    links: [ISSUE(262)],
  },
  {
    id: "#263",
    title: "Green-light callback",
    status: "shipped",
    timeframe: "Loop · TDD gate",
    summary:
      "Emits check.satisfied only when every linked scenario has passed N consecutive runs with zero flakes and complete artifacts — the signal that unblocks a TasksAI task for completion.",
    tags: ["epic #269"],
    links: [ISSUE(263), ISSUE(269)],
  },

  // ── Production reliability, Sept 2026 ─────────────────────────────
  {
    id: "Reliability",
    title: "Stuck-run and production-build fixes",
    status: "shipped",
    timeframe: "25 Sep 2026",
    summary:
      "A health-check fixture navigating to a raw JSON URL, a duplicate variable declaration crashing SSO smoke tests, and two rounds of missing runtime assets (TestCafe reads template/device files off disk, which a standalone Docker build was pruning) — all diagnosed live against the running app and VPS logs, not guessed at.",
    tags: ["reliability"],
    links: [PR(618), PR(621), PR(623), PR(627)],
  },

  // ── Issue tracking rework, Sept 2026 ───────────────────────────────
  {
    id: "Issues-UX",
    title: "Junior-friendly issue reports, filters & related-issue tracking",
    status: "shipped",
    timeframe: "25 Sep 2026",
    summary:
      "A generated GitHub issue now follows this repo's own bug_report.md structure, written for someone new to the codebase. The Issues page gained status/GitHub-state/fixture filters, search, and per-app open/closed/draft counts; issues from the same test case are now cross-linked everywhere — a badge in the list, a section on the issue page, and in the body filed on GitHub.",
    tags: ["triage", "ux"],
    links: [ISSUE(624), PR(625), PR(626)],
  },

  // Forward work is tracked by the AI-native quality assistant epic (#629).
  // #549 is the redaction foundation every other item routes through and
  // should land first; the rest can proceed in any order after that.
  {
    id: "#549",
    title: "Redact secrets before captured text reaches OpenAI",
    status: "planned",
    timeframe: "AI assistant · foundation",
    summary:
      "An E2E test's captured error can contain a stack trace, a response body, or a header value from the app under test — nothing rules out a leaked token or secret. Redacts emails, API-key-shaped tokens, JWTs, and connection strings before any AI feature sends captured text to a model.",
    tags: ["ai", "safety", "epic #629"],
    links: [ISSUE(549)],
  },
  {
    id: "#546",
    title: "AI-suggested selector fixes from failure DOM snapshots",
    status: "planned",
    timeframe: "AI assistant",
    summary:
      "Testora already captures the page's DOM at the moment of failure and discards it after a human reads it once. A broken selector — the most common cause of E2E flakiness — is diagnosable from exactly that data: propose a corrected selector and a plain-language explanation, always a reviewed draft, never auto-applied.",
    tags: ["ai", "triage", "epic #629"],
    links: [ISSUE(546)],
  },
  {
    id: "#547",
    title: "Run-level AI failure clustering",
    status: "planned",
    timeframe: "AI assistant",
    summary:
      "A run with a dozen failures often has one shared root cause. Groups simultaneous failures in a run into likely-shared-cause clusters with one explanation each, instead of triaging each result in isolation.",
    tags: ["ai", "triage", "epic #629"],
    links: [ISSUE(547)],
  },
  {
    id: "#628",
    title: "Cross-run AI summary of a test case's related-issue history",
    status: "planned",
    timeframe: "AI assistant",
    summary:
      "The time-spread complement to run-level clustering: summarizes the pattern across a test case's related issues (built on the related-issue tracking already shipped above) — same test, different failures, days or weeks apart.",
    tags: ["ai", "triage", "epic #629"],
    links: [ISSUE(628)],
  },
  {
    id: "#548",
    title: "AI-assisted test-case authoring from a plain-language description",
    status: "planned",
    timeframe: "AI assistant",
    summary:
      "Describe a test flow in plain language and get a draft test case, validated through the exact same schema a hand-authored one already goes through — no new trust surface, always reviewed before it's saved.",
    tags: ["ai", "authoring", "epic #629"],
    links: [ISSUE(548)],
  },
];
