import type { RoadmapItem } from "@asafarim/ui";

const ISSUE = (n: number) => ({
  label: `#${n}`,
  href: `https://github.com/AliSafari-IT/asafarim-platform/issues/${n}`,
});

/**
 * Testora's direction. The left column is what already runs in the app; the
 * right column is the "autonomous quality loop" — a bidirectional
 * integration with TasksAI (tracking epic #269).
 */
export const roadmapItems: RoadmapItem[] = [
  {
    id: "Authoring",
    title: "Requirements → suites → fixtures → cases",
    status: "shipped",
    summary:
      "The full authoring model — functional requirements, test suites, fixtures, and cases (single, multi, or raw scripted) — persisted in Testora's own PostgreSQL, kept separate from the shared platform schema.",
    tags: ["core"],
  },
  {
    id: "Execution",
    title: "Live TestCafe execution with streamed progress",
    status: "shipped",
    summary:
      "Signed-in users drive a real headless browser against local or remote targets and watch run progress stream in over SSE. Repeat runs per case, and a per-fixture flaky flag that adds retries.",
  },
  {
    id: "Targets",
    title: "Per-app target environments",
    status: "shipped",
    summary:
      "Each app under test carries its own Local / Remote (and user-added) environments; switching apps offers that app's own targets. Seeded entries are reconciled from code, custom ones are preserved.",
  },
  {
    id: "Results",
    title: "Results, failure screenshots & AI issue drafting",
    status: "shipped",
    summary:
      "Every run stored with pass/fail status, duration, and a failure screenshot captured automatically. A failing result becomes a ready-to-file GitHub issue — drafted by AI when a key is set, from a deterministic template otherwise — and published to GitHub with two-way open/closed state.",
    tags: ["triage"],
  },
  {
    id: "Access",
    title: "Public landing, private apps-under-test",
    status: "shipped",
    summary:
      "A public catalog and marketing surface; individual apps under test can be locked behind a key, with their catalog and results withheld server-side until unlocked.",
  },
  {
    id: "Benchmark",
    title: "Committed benchmark evidence",
    status: "in-progress",
    summary:
      "The benchmark results published on Showcase are committed snapshots from a seeded sample app. Broadening coverage and keeping the snapshots current is ongoing.",
    tags: ["showcase"],
  },

  // ── Autonomous quality loop — epic #269 ──────────────────────────
  {
    id: "#258",
    title: "Run-artifact bundle API",
    status: "planned",
    timeframe: "Loop · foundation",
    summary:
      "Export one result as a versioned JSON bundle — error, step/assertion timeline, screenshot, and a reference to the previous passing run — so another system can consume a failure cleanly. Gated by the same visibility check the results page uses.",
    tags: ["epic #269"],
    links: [ISSUE(258), ISSUE(268)],
  },
  {
    id: "#259",
    title: "Richer failure artifacts",
    status: "planned",
    timeframe: "Loop · foundation",
    summary:
      "Capture a DOM snapshot and a structured step timeline (and an opt-in video) at the point of failure, stored in object storage with a retention window instead of multi-MB data URLs on the result row.",
    tags: ["epic #269"],
    links: [ISSUE(259)],
  },
  {
    id: "#260",
    title: "Automatic flake detection + quarantine",
    status: "planned",
    timeframe: "Loop",
    summary:
      "Derive flakiness from fail-then-pass across repeat runs (today it's a manual flag), and add a quarantine state that keeps a flaky test out of the blocking set while it's still investigated.",
    tags: ["epic #269"],
    links: [ISSUE(260)],
  },
  {
    id: "#261",
    title: "Outbound signed webhooks",
    status: "planned",
    timeframe: "Loop",
    summary:
      "An HMAC-signed dispatcher for run.completed / regression.detected / flake.detected / check.satisfied, with a delivery log and retries — the channel that tells TasksAI something happened.",
    tags: ["epic #269"],
    links: [ISSUE(261)],
  },
  {
    id: "#262",
    title: "Inbound provisioning + pending scenarios",
    status: "exploring",
    timeframe: "Loop · TDD gate",
    summary:
      "Accept a request from TasksAI to register pending test scenarios for a feature's acceptance criteria — scaffolds generated by the existing generators, marked pending until real assertions land.",
    tags: ["epic #269"],
    links: [ISSUE(262)],
  },
  {
    id: "#263",
    title: "Green-light callback",
    status: "exploring",
    timeframe: "Loop · TDD gate",
    summary:
      "Emit check.satisfied only when every linked scenario has passed N consecutive runs with zero flakes and complete artifacts — the signal that unblocks a TasksAI task for completion.",
    tags: ["epic #269"],
    links: [ISSUE(263), ISSUE(269)],
  },
];
