// EduMatch presentation seed definitions. Every identity and domain row is
// synthetic, deterministic, and owned through the reserved demo namespace.

export const EDUMATCH_DEFINITION_VERSION = "2.1.0";
export const EDUMATCH_DEMO_EMAIL_DOMAIN = "@gmail.com";
export const EDUMATCH_DEMO_EMAIL_PREFIX = "asafarim+edu";
export const EDUMATCH_ID_PREFIX = "seed-edumatch-";

const email = (legacyLocal: string) => {
  const match = /^demo\.(student|tutor|parent|admin)(\d{2})$/.exec(legacyLocal);
  if (!match) throw new Error(`Invalid EduMatch demo identity: ${legacyLocal}`);
  return `${EDUMATCH_DEMO_EMAIL_PREFIX}${match[1]}${match[2]}${EDUMATCH_DEMO_EMAIL_DOMAIN}`;
};
const legacyEmail = (legacyLocal: string) => `${legacyLocal}@edumatch.demo`;
export const edumatchSeedId = (kind: string, key: string) =>
  `${EDUMATCH_ID_PREFIX}${kind}-${key.toLowerCase()}`;

export interface DemoStudent {
  key: string;
  email: string;
  name: string;
  gradeLevel: "K12" | "UNDERGRAD" | "GRAD";
  subjects: string[];
  preferredLanguage: string;
  dateOfBirth: string;
  parentKey?: string;
  avatar?: string;
  home?: { city: string; lat: number; lng: number };
}

export interface DemoParent {
  key: string;
  email: string;
  name: string;
}

export interface DemoAdmin {
  key: string;
  email: string;
  name: string;
  emphasis: string;
}

export interface DemoTutor {
  key: string;
  email: string;
  name: string;
  subjects: string[];
  levels: Array<"K12" | "UNDERGRAD" | "GRAD">;
  languages: string[];
  hourlyRateCents: number;
  onlineOnly: boolean;
  serviceRadiusKm: number;
  home?: { city: string; lat: number; lng: number };
  verification: "VERIFIED" | "PENDING" | "NEEDS_CHANGES" | "REJECTED";
  clearedForMinors: boolean;
  ratingAvg: number;
  ratingCount: number;
  teachingStyle: "STRUCTURED" | "EXAM_FOCUSED" | "EXPLORATORY" | "PATIENT";
  responseMinutes: number | null;
  stripeState: "ENABLED" | "REFRESH_REQUIRED" | "NOT_STARTED";
  wallet: {
    balanceCents: number;
    pendingCents: number;
    lastPayoutDaysAgo?: number;
  };
}

export interface DemoBrief {
  key: string;
  studentKey: string;
  subject: string;
  topic: string;
  educationalLevel: "K12" | "UNDERGRAD" | "GRAD";
  language: string;
  mode: "ONLINE" | "IN_PERSON" | "EITHER";
  status: "DRAFT" | "CONFIRMED" | "MATCHED" | "ARCHIVED";
  triage: "SELF_STUDY" | "TUTOR_RECOMMENDED" | "NEEDS_DIAGNOSTIC";
  objective: string;
  difficulty: string;
  city?: string;
  accessibilityNeeds?: string;
}

export interface DemoMatch {
  tutor: string;
  rotation?: boolean;
}

export const EDUMATCH_PARENTS: DemoParent[] = [
  { key: "P01", email: email("demo.parent01"), name: "Nadia Jacobs" },
  { key: "P02", email: email("demo.parent02"), name: "Marc Bernard" },
  { key: "P03", email: email("demo.parent03"), name: "Fatima Rahman" },
  { key: "P04", email: email("demo.parent04"), name: "Eva Claes" },
  { key: "P05", email: email("demo.parent05"), name: "David Fischer" },
];

export const EDUMATCH_STUDENTS: DemoStudent[] = [
  {
    key: "S01",
    email: email("demo.student01"),
    name: "Noor Vermeulen",
    gradeLevel: "UNDERGRAD",
    subjects: ["Mathematics", "Physics"],
    preferredLanguage: "nl",
    dateOfBirth: "2006-04-18",
    home: { city: "Brussels", lat: 50.8503, lng: 4.3517 },
  },
  {
    key: "S02",
    email: email("demo.student02"),
    name: "Mila Jacobs",
    gradeLevel: "K12",
    subjects: ["Mathematics"],
    preferredLanguage: "nl",
    dateOfBirth: "2012-03-10",
    parentKey: "P01",
    avatar: "/avatars/students/nova.svg",
    home: { city: "Leuven", lat: 50.8798, lng: 4.7005 },
  },
  {
    key: "S03",
    email: email("demo.student03"),
    name: "Elias Bernard",
    gradeLevel: "K12",
    subjects: ["Computer Science"],
    preferredLanguage: "fr",
    dateOfBirth: "2008-02-14",
    home: { city: "Brussels", lat: 50.8466, lng: 4.3528 },
  },
  {
    key: "S04",
    email: email("demo.student04"),
    name: "Leonie Dubois",
    gradeLevel: "K12",
    subjects: ["French"],
    preferredLanguage: "fr",
    dateOfBirth: "2014-05-21",
    parentKey: "P01",
    avatar: "/avatars/students/palette.svg",
  },
  {
    key: "S05",
    email: email("demo.student05"),
    name: "Samir Rahman",
    gradeLevel: "K12",
    subjects: ["English", "Study Skills"],
    preferredLanguage: "en",
    dateOfBirth: "2011-09-02",
    parentKey: "P03",
    avatar: "/avatars/students/rocket.svg",
  },
  {
    key: "S06",
    email: email("demo.student06"),
    name: "Hannah Kruger",
    gradeLevel: "UNDERGRAD",
    subjects: ["Statistics"],
    preferredLanguage: "de",
    dateOfBirth: "2004-07-12",
  },
  {
    key: "S07",
    email: email("demo.student07"),
    name: "Yara Demir",
    gradeLevel: "GRAD",
    subjects: ["Computer Science"],
    preferredLanguage: "en",
    dateOfBirth: "2000-11-03",
  },
  {
    key: "S08",
    email: email("demo.student08"),
    name: "Mateo Silva",
    gradeLevel: "UNDERGRAD",
    subjects: ["Physics"],
    preferredLanguage: "fr",
    dateOfBirth: "2007-01-30",
  },
  {
    key: "S09",
    email: email("demo.student09"),
    name: "Emma Vos",
    gradeLevel: "K12",
    subjects: ["Mathematics"],
    preferredLanguage: "nl",
    dateOfBirth: "2010-01-02",
  },
  {
    key: "S10",
    email: email("demo.student10"),
    name: "Idris El Amrani",
    gradeLevel: "K12",
    subjects: ["Chemistry"],
    preferredLanguage: "fr",
    dateOfBirth: "2008-06-09",
  },
  {
    key: "S11",
    email: email("demo.student11"),
    name: "Clara Martin",
    gradeLevel: "UNDERGRAD",
    subjects: ["French"],
    preferredLanguage: "fr",
    dateOfBirth: "2005-08-25",
  },
  {
    key: "S12",
    email: email("demo.student12"),
    name: "Finn Muller",
    gradeLevel: "GRAD",
    subjects: ["Statistics"],
    preferredLanguage: "en",
    dateOfBirth: "2002-12-17",
  },
  {
    key: "S13",
    email: email("demo.student13"),
    name: "Zoe Claes",
    gradeLevel: "K12",
    subjects: ["Biology"],
    preferredLanguage: "nl",
    dateOfBirth: "2013-04-01",
    parentKey: "P04",
    avatar: "seed/avatars/s13.webp",
    home: { city: "Mechelen", lat: 51.0259, lng: 4.4776 },
  },
  {
    key: "S14",
    email: email("demo.student14"),
    name: "Adam Fischer",
    gradeLevel: "K12",
    subjects: ["German"],
    preferredLanguage: "de",
    dateOfBirth: "2015-02-22",
    parentKey: "P05",
    avatar: "/avatars/students/default.svg",
  },
  {
    key: "S15",
    email: email("demo.student15"),
    name: "Ines Laurent",
    gradeLevel: "GRAD",
    subjects: ["Statistics"],
    preferredLanguage: "fr",
    dateOfBirth: "1995-10-08",
  },
  {
    key: "S16",
    email: email("demo.student16"),
    name: "Ravi Patel",
    gradeLevel: "UNDERGRAD",
    subjects: ["Physics"],
    preferredLanguage: "en",
    dateOfBirth: "2006-01-15",
  },
  {
    key: "S17",
    email: email("demo.student17"),
    name: "Nora Smit",
    gradeLevel: "UNDERGRAD",
    subjects: ["Economics"],
    preferredLanguage: "nl",
    dateOfBirth: "2008-03-19",
  },
  {
    key: "S18",
    email: email("demo.student18"),
    name: "Liam O'Connor",
    gradeLevel: "UNDERGRAD",
    subjects: ["English"],
    preferredLanguage: "en",
    dateOfBirth: "2003-09-11",
  },
  {
    key: "S19",
    email: email("demo.student19"),
    name: "Sarah De Wilde",
    gradeLevel: "GRAD",
    subjects: ["Computer Science"],
    preferredLanguage: "nl",
    dateOfBirth: "1997-02-05",
  },
  {
    key: "S20",
    email: email("demo.student20"),
    name: "Omar Haddad",
    gradeLevel: "UNDERGRAD",
    subjects: ["Accounting"],
    preferredLanguage: "en",
    dateOfBirth: "1992-07-27",
  },
  {
    key: "S21",
    email: email("demo.student21"),
    name: "Chloe Renard",
    gradeLevel: "K12",
    subjects: ["French"],
    preferredLanguage: "fr",
    dateOfBirth: "2008-10-13",
  },
  {
    key: "S22",
    email: email("demo.student22"),
    name: "Daan Bakker",
    gradeLevel: "GRAD",
    subjects: ["Computer Science"],
    preferredLanguage: "nl",
    dateOfBirth: "2001-06-28",
  },
  {
    key: "S23",
    email: email("demo.student23"),
    name: "Aya Schmidt",
    gradeLevel: "K12",
    subjects: [],
    preferredLanguage: "de",
    dateOfBirth: "2010-08-16",
    avatar: "/avatars/students/cosmo.svg",
  },
  {
    key: "S24",
    email: email("demo.student24"),
    name: "Jonas Meyer",
    gradeLevel: "UNDERGRAD",
    subjects: ["Economics"],
    preferredLanguage: "de",
    dateOfBirth: "2005-11-24",
  },
  {
    key: "S25",
    email: email("demo.student25"),
    name: "Maya Johnson",
    gradeLevel: "GRAD",
    subjects: ["Statistics"],
    preferredLanguage: "en",
    dateOfBirth: "1998-04-06",
  },
  {
    key: "S26",
    email: email("demo.student26"),
    name: "Theo Laurent",
    gradeLevel: "UNDERGRAD",
    subjects: ["Art"],
    preferredLanguage: "fr",
    dateOfBirth: "2007-09-29",
    home: { city: "Namur", lat: 50.4674, lng: 4.8718 },
  },
  {
    key: "S27",
    email: email("demo.student27"),
    name: "Lina Peeters",
    gradeLevel: "K12",
    subjects: ["Biology"],
    preferredLanguage: "nl",
    dateOfBirth: "2009-12-04",
  },
];

export const EDUMATCH_TUTORS: DemoTutor[] = [
  {
    key: "T01",
    email: email("demo.tutor01"),
    name: "Amira Vandenberg",
    subjects: ["Mathematics", "Physics"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["nl", "en"],
    hourlyRateCents: 4500,
    onlineOnly: false,
    serviceRadiusKm: 30,
    home: { city: "Brussels", lat: 50.8503, lng: 4.3517 },
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.8,
    ratingCount: 12,
    teachingStyle: "STRUCTURED",
    responseMinutes: 18,
    stripeState: "ENABLED",
    wallet: { balanceCents: 12850, pendingCents: 0 },
  },
  {
    key: "T02",
    email: email("demo.tutor02"),
    name: "Lucas De Smet",
    subjects: ["Chemistry", "Biology"],
    levels: ["K12"],
    languages: ["nl", "en"],
    hourlyRateCents: 3800,
    onlineOnly: false,
    serviceRadiusKm: 25,
    home: { city: "Leuven", lat: 50.8798, lng: 4.7005 },
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.6,
    ratingCount: 8,
    teachingStyle: "PATIENT",
    responseMinutes: 35,
    stripeState: "ENABLED",
    wallet: { balanceCents: 0, pendingCents: 6460 },
  },
  {
    key: "T03",
    email: email("demo.tutor03"),
    name: "Sofia Martins",
    subjects: ["Computer Science", "Statistics"],
    levels: ["UNDERGRAD", "GRAD"],
    languages: ["en", "fr"],
    hourlyRateCents: 5200,
    onlineOnly: false,
    serviceRadiusKm: 20,
    home: { city: "Brussels", lat: 50.836, lng: 4.365 },
    verification: "VERIFIED",
    clearedForMinors: false,
    ratingAvg: 4.7,
    ratingCount: 6,
    teachingStyle: "EXPLORATORY",
    responseMinutes: 42,
    stripeState: "ENABLED",
    wallet: { balanceCents: 0, pendingCents: 0, lastPayoutDaysAgo: 4 },
  },
  {
    key: "T04",
    email: email("demo.tutor04"),
    name: "Julien Lambert",
    subjects: ["French", "English"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["fr", "en"],
    hourlyRateCents: 4200,
    onlineOnly: false,
    serviceRadiusKm: 15,
    home: { city: "Brussels", lat: 50.861, lng: 4.33 },
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.5,
    ratingCount: 4,
    teachingStyle: "PATIENT",
    responseMinutes: 60,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T05",
    email: email("demo.tutor05"),
    name: "Aisha El Mansouri",
    subjects: ["English", "Study Skills"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["fr", "en", "nl"],
    hourlyRateCents: 4000,
    onlineOnly: false,
    serviceRadiusKm: 20,
    home: { city: "Mechelen", lat: 51.0259, lng: 4.4776 },
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.9,
    ratingCount: 3,
    teachingStyle: "PATIENT",
    responseMinutes: 25,
    stripeState: "ENABLED",
    wallet: { balanceCents: 3400, pendingCents: 0 },
  },
  {
    key: "T06",
    email: email("demo.tutor06"),
    name: "Bram Peeters",
    subjects: ["Economics", "Accounting"],
    levels: ["UNDERGRAD"],
    languages: ["nl", "en"],
    hourlyRateCents: 4800,
    onlineOnly: false,
    serviceRadiusKm: 15,
    home: { city: "Antwerp", lat: 51.2194, lng: 4.4025 },
    verification: "VERIFIED",
    clearedForMinors: false,
    ratingAvg: 4,
    ratingCount: 2,
    teachingStyle: "EXAM_FOCUSED",
    responseMinutes: 90,
    stripeState: "REFRESH_REQUIRED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T07",
    email: email("demo.tutor07"),
    name: "Lea Weber",
    subjects: ["German", "History"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["de", "fr", "en"],
    hourlyRateCents: 3600,
    onlineOnly: false,
    serviceRadiusKm: 40,
    home: { city: "Luxembourg", lat: 49.6116, lng: 6.1319 },
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 5,
    ratingCount: 1,
    teachingStyle: "STRUCTURED",
    responseMinutes: 75,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T08",
    email: email("demo.tutor08"),
    name: "Noa Janssen",
    subjects: ["Mathematics", "Computer Science"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["nl", "en"],
    hourlyRateCents: 3200,
    onlineOnly: false,
    serviceRadiusKm: 30,
    home: { city: "Brussels", lat: 50.872, lng: 4.37 },
    verification: "VERIFIED",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "EXPLORATORY",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T09",
    email: email("demo.tutor09"),
    name: "Elena Rossi",
    subjects: ["Art", "Design"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["fr", "en"],
    hourlyRateCents: 3500,
    onlineOnly: false,
    serviceRadiusKm: 10,
    home: { city: "Brussels", lat: 50.845, lng: 4.38 },
    verification: "PENDING",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "EXPLORATORY",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T10",
    email: email("demo.tutor10"),
    name: "Tom Becker",
    subjects: ["Biology", "Chemistry"],
    levels: ["K12"],
    languages: ["de", "en"],
    hourlyRateCents: 3400,
    onlineOnly: false,
    serviceRadiusKm: 10,
    home: { city: "Luxembourg", lat: 49.62, lng: 6.12 },
    verification: "PENDING",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "STRUCTURED",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T11",
    email: email("demo.tutor11"),
    name: "Priya Nair",
    subjects: ["Mathematics", "Physics"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["en", "nl"],
    hourlyRateCents: 6000,
    onlineOnly: true,
    serviceRadiusKm: 0,
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.9,
    ratingCount: 10,
    teachingStyle: "EXAM_FOCUSED",
    responseMinutes: 12,
    stripeState: "ENABLED",
    wallet: { balanceCents: 9600, pendingCents: 0 },
  },
  {
    key: "T12",
    email: email("demo.tutor12"),
    name: "Marcus Okafor",
    subjects: ["Chemistry", "Biology"],
    levels: ["K12"],
    languages: ["en", "fr"],
    hourlyRateCents: 4400,
    onlineOnly: true,
    serviceRadiusKm: 0,
    verification: "VERIFIED",
    clearedForMinors: true,
    ratingAvg: 4.4,
    ratingCount: 5,
    teachingStyle: "PATIENT",
    responseMinutes: 50,
    stripeState: "ENABLED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T13",
    email: email("demo.tutor13"),
    name: "Sofia Chen",
    subjects: ["Computer Science", "Statistics"],
    levels: ["UNDERGRAD", "GRAD"],
    languages: ["en", "de"],
    hourlyRateCents: 3000,
    onlineOnly: true,
    serviceRadiusKm: 0,
    verification: "VERIFIED",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "EXPLORATORY",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T14",
    email: email("demo.tutor14"),
    name: "Nadia Haddad",
    subjects: ["English", "Study Skills"],
    levels: ["K12", "UNDERGRAD"],
    languages: ["fr", "en"],
    hourlyRateCents: 2800,
    onlineOnly: true,
    serviceRadiusKm: 0,
    verification: "NEEDS_CHANGES",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "PATIENT",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
  {
    key: "T15",
    email: email("demo.tutor15"),
    name: "Viktor Klein",
    subjects: ["Economics", "Accounting"],
    levels: ["UNDERGRAD", "GRAD"],
    languages: ["de", "en"],
    hourlyRateCents: 7000,
    onlineOnly: true,
    serviceRadiusKm: 0,
    verification: "REJECTED",
    clearedForMinors: false,
    ratingAvg: 0,
    ratingCount: 0,
    teachingStyle: "EXAM_FOCUSED",
    responseMinutes: null,
    stripeState: "NOT_STARTED",
    wallet: { balanceCents: 0, pendingCents: 0 },
  },
];

export const EDUMATCH_ADMINS: DemoAdmin[] = [
  {
    key: "A01",
    email: email("demo.admin01"),
    name: "Alex Morgan",
    emphasis: "Operations and matching",
  },
  {
    key: "A02",
    email: email("demo.admin02"),
    name: "Camille Janssen",
    emphasis: "Verification and safeguarding",
  },
  {
    key: "A03",
    email: email("demo.admin03"),
    name: "Robin Schneider",
    emphasis: "Support and finance",
  },
];

export const EDUMATCH_BRIEFS: DemoBrief[] = [
  {
    key: "S01",
    studentKey: "S01",
    subject: "Mathematics",
    topic: "Second-order differential equations",
    educationalLevel: "UNDERGRAD",
    language: "nl",
    mode: "EITHER",
    status: "ARCHIVED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Solve homogeneous and particular equations before the exam.",
    difficulty: "Choosing the correct particular-solution form.",
  },
  {
    key: "S02",
    studentKey: "S02",
    subject: "Mathematics",
    topic: "Quadratic equations",
    educationalLevel: "K12",
    language: "nl",
    mode: "IN_PERSON",
    status: "MATCHED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Factor and solve quadratics independently.",
    difficulty: "Connecting graphs, factors, and roots.",
    city: "Leuven",
  },
  {
    key: "S03",
    studentKey: "S03",
    subject: "Computer Science",
    topic: "Recursion",
    educationalLevel: "K12",
    language: "fr",
    mode: "ONLINE",
    status: "MATCHED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Trace and write recursive functions.",
    difficulty: "Understanding base cases and the call stack.",
  },
  {
    key: "S05",
    studentKey: "S05",
    subject: "Study Skills",
    topic: "Reading and note taking",
    educationalLevel: "K12",
    language: "en",
    mode: "EITHER",
    status: "DRAFT",
    triage: "NEEDS_DIAGNOSTIC",
    objective: "Find a study method that works for longer texts.",
    difficulty: "Losing the main idea while reading.",
    accessibilityNeeds:
      "Dyslexia-friendly materials and extra processing time.",
  },
  {
    key: "S06",
    studentKey: "S06",
    subject: "Statistics",
    topic: "Confidence intervals",
    educationalLevel: "UNDERGRAD",
    language: "de",
    mode: "ONLINE",
    status: "CONFIRMED",
    triage: "SELF_STUDY",
    objective: "Interpret confidence intervals correctly.",
    difficulty: "Confusing probability statements about parameters.",
  },
  {
    key: "S07",
    studentKey: "S07",
    subject: "Computer Science",
    topic: "Distributed systems",
    educationalLevel: "GRAD",
    language: "en",
    mode: "EITHER",
    status: "DRAFT",
    triage: "TUTOR_RECOMMENDED",
    objective: "Prepare for a distributed systems oral exam.",
    difficulty: "Needs clarification about the exact weak area.",
  },
  {
    key: "S09",
    studentKey: "S09",
    subject: "Mathematics",
    topic: "Calculus",
    educationalLevel: "K12",
    language: "nl",
    mode: "EITHER",
    status: "MATCHED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Understand derivatives before final exams.",
    difficulty: "Translating word problems into rates of change.",
  },
  {
    key: "S11",
    studentKey: "S11",
    subject: "French",
    topic: "Academic writing",
    educationalLevel: "UNDERGRAD",
    language: "fr",
    mode: "ONLINE",
    status: "MATCHED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Structure a clear argumentative essay.",
    difficulty: "Paragraph cohesion and transitions.",
  },
  {
    key: "S12",
    studentKey: "S12",
    subject: "Statistics",
    topic: "Bayesian inference",
    educationalLevel: "GRAD",
    language: "en",
    mode: "ONLINE",
    status: "ARCHIVED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Build and interpret a Bayesian model.",
    difficulty: "Selecting and explaining priors.",
  },
  {
    key: "S15",
    studentKey: "S15",
    subject: "Statistics",
    topic: "Regression diagnostics",
    educationalLevel: "GRAD",
    language: "fr",
    mode: "EITHER",
    status: "ARCHIVED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Diagnose model assumptions in a thesis dataset.",
    difficulty: "Interpreting residual plots.",
  },
  {
    key: "S16",
    studentKey: "S16",
    subject: "Physics",
    topic: "Electromagnetism",
    educationalLevel: "UNDERGRAD",
    language: "en",
    mode: "ONLINE",
    status: "MATCHED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Prepare for the electromagnetism exam.",
    difficulty: "Applying Maxwell equations.",
  },
  {
    key: "S17",
    studentKey: "S17",
    subject: "Economics",
    topic: "Microeconomics",
    educationalLevel: "UNDERGRAD",
    language: "nl",
    mode: "EITHER",
    status: "CONFIRMED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Understand consumer choice.",
    difficulty: "Indifference curves and constraints.",
  },
  {
    key: "S18",
    studentKey: "S18",
    subject: "English",
    topic: "Academic integrity",
    educationalLevel: "UNDERGRAD",
    language: "en",
    mode: "ONLINE",
    status: "DRAFT",
    triage: "SELF_STUDY",
    objective: "Learn how to plan an original essay.",
    difficulty: "Asked for an answer key instead of learning support.",
  },
  {
    key: "S19",
    studentKey: "S19",
    subject: "Computer Science",
    topic: "Data structures",
    educationalLevel: "GRAD",
    language: "nl",
    mode: "EITHER",
    status: "CONFIRMED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Review advanced tree structures.",
    difficulty: "Comparing balancing strategies.",
    accessibilityNeeds: "Live captions and written summaries.",
  },
  {
    key: "S21",
    studentKey: "S21",
    subject: "French",
    topic: "Pronunciation",
    educationalLevel: "K12",
    language: "fr",
    mode: "ONLINE",
    status: "DRAFT",
    triage: "SELF_STUDY",
    objective: "Improve pronunciation from an uploaded recording.",
    difficulty: "Nasal vowels.",
  },
  {
    key: "S22",
    studentKey: "S22",
    subject: "Computer Science",
    topic: "Database query plans",
    educationalLevel: "GRAD",
    language: "nl",
    mode: "ONLINE",
    status: "CONFIRMED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Read the uploaded query-plan screenshot.",
    difficulty: "Identifying the costly operation.",
  },
  {
    key: "S25",
    studentKey: "S25",
    subject: "Statistics",
    topic: "Experimental design",
    educationalLevel: "GRAD",
    language: "en",
    mode: "ONLINE",
    status: "ARCHIVED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Design and analyse a reproducible experiment.",
    difficulty: "Power analysis and confounders.",
  },
  {
    key: "S26",
    studentKey: "S26",
    subject: "Art",
    topic: "Portfolio composition",
    educationalLevel: "UNDERGRAD",
    language: "fr",
    mode: "IN_PERSON",
    status: "CONFIRMED",
    triage: "TUTOR_RECOMMENDED",
    objective: "Prepare a balanced admissions portfolio.",
    difficulty: "Sequencing pieces into a coherent story.",
    city: "Namur",
  },
];

export const EDUMATCH_MATCH_PLAN: Record<string, DemoMatch[]> = {
  S01: [{ tutor: "T01" }, { tutor: "T11" }],
  S02: [{ tutor: "T01" }],
  S03: [{ tutor: "T08" }, { tutor: "T03" }, { tutor: "T13", rotation: true }],
  S09: [{ tutor: "T01" }, { tutor: "T11" }],
  S11: [{ tutor: "T04" }],
  S12: [{ tutor: "T03" }, { tutor: "T13" }],
  S15: [{ tutor: "T03" }, { tutor: "T13" }],
  S16: [{ tutor: "T01" }, { tutor: "T11" }],
  S25: [{ tutor: "T03" }, { tutor: "T13", rotation: true }],
};

export const EDUMATCH_CHAIN_IDS = {
  inquiry: edumatchSeedId("inquiry", "S01"),
  aiResponse: edumatchSeedId("ai", "S01"),
  quoteRequest: edumatchSeedId("request", "S01"),
  transaction: edumatchSeedId("transaction", "T01-01-charge"),
  notification: edumatchSeedId("notification", "S01-0"),
} as const;

export const EDUMATCH_DEMO_EMAILS = [
  ...EDUMATCH_STUDENTS.map((item) => item.email),
  ...EDUMATCH_TUTORS.map((item) => item.email),
  ...EDUMATCH_PARENTS.map((item) => item.email),
  ...EDUMATCH_ADMINS.map((item) => item.email),
];

export const EDUMATCH_LEGACY_DEMO_EMAILS = [
  ...EDUMATCH_STUDENTS.map((student) =>
    legacyEmail(`demo.student${student.key.slice(1)}`)
  ),
  ...EDUMATCH_TUTORS.map((tutor) =>
    legacyEmail(`demo.tutor${tutor.key.slice(1)}`)
  ),
  ...EDUMATCH_PARENTS.map((parent) =>
    legacyEmail(`demo.parent${parent.key.slice(1)}`)
  ),
  ...EDUMATCH_ADMINS.map((admin) =>
    legacyEmail(`demo.admin${admin.key.slice(1)}`)
  ),
  // The original small fixture used unpadded aliases for its first three
  // students and tutors. Keep these exact addresses allowlisted for in-place
  // migration; no other @edumatch.demo identity is seed-owned.
  ...[1, 2, 3].flatMap((number) => [
    legacyEmail(`demo.student${number}`),
    legacyEmail(`demo.tutor${number}`),
  ]),
];

export const EDUMATCH_DEFINITIONS = {
  version: EDUMATCH_DEFINITION_VERSION,
  students: EDUMATCH_STUDENTS,
  tutors: EDUMATCH_TUTORS,
  parents: EDUMATCH_PARENTS,
  admins: EDUMATCH_ADMINS,
  briefs: EDUMATCH_BRIEFS,
  matchPlan: EDUMATCH_MATCH_PLAN,
  chainIds: EDUMATCH_CHAIN_IDS,
};
